site_name: engels74.net
site_url: https://engels74.net
site_author: engels74
site_description: Documentation for Docker images maintained by engels74.
copyright: 'Copyright &copy; 2023-2026 engels74<br>Based on <a href="https://hotio.dev" target="_blank" rel="noopener">hotio.dev</a>. Logos based on work by <a href="https://www.flaticon.com/authors/freepik" target="_blank" rel="noopener">Freepik</a> from <a href="https://www.flaticon.com" target="_blank" rel="noopener">flaticon.com</a> and <a href="https://freeicons.io/profile/6200" target="_blank" rel="noopener">Soni Sokell</a> on <a href="https://freeicons.io" target="_blank" rel="noopener">freeicons.io</a>'
repo_name: engels74
repo_url: https://github.com/engels74
edit_uri: 'hweb/edit/master/docs'
site_dir: .build
docs_dir: docs

extra:
  social:
  - icon: fontawesome/solid/heart
    link: 'https://github.com/sponsors/mrhotio'
    name: Donate to Hotio
  - icon: fontawesome/brands/github
    link: 'https://github.com/engels74'
    name: GitHub

extra_css:
  - stylesheets/extra-13.css
  - stylesheets/extra-custom.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/tagcopy.js

theme:
  icon:
    repo: fontawesome/brands/github
    annotation: material/information
  favicon: img/engels74.svg
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tooltips
    - content.tabs.link
    - toc.follow
  language: en
  logo: img/engels74.svg
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: DM Sans
    code: JetBrains Mono
  custom_dir: overrides

markdown_extensions:
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - toc:
      permalink: true
  - admonition
  - abbr
  - pymdownx.blocks.caption
  - tables

nav:
- Home: index.md
- Containers:
  - Base Images:
    - engels74/base-image: containers/base-image.md
  - Apps:
    - engels74/caddy: containers/caddy.md
    - engels74/overseerr-anime: containers/overseerr-anime.md
    - engels74/qbittorrent: containers/qbittorrent.md
    - engels74/qflood: containers/qflood.md
    - engels74/sabnzbd: containers/sabnzbd.md
  - engels74:
    - engels74/obzorarr: containers/obzorarr.md
    - engels74/tgraph-bot: containers/tgraph-bot.md
- FAQ: faq.md
